:default:
  :colorize: false
  :console_inline: false
  :log_trace: false
  :level: info
  :type: file
  :pattern: "%d %.8X{session} [%c] [%.1l] %m\n"

:production:
  :filename: "production.log"

:development:
  :colorize: true
  :console_inline: true
  :level: debug
  :filename: "development.log"

:test:
  :level: debug
  :filename: "test.log"
  :truncate: true
