#
-   name: "Configure foreman proxy server on Debian"
    hosts: [proxy]
    vars:
        - foreman_master_hostname: foreman.weedtime.cz

    tasks:
        -   debug:
                msg: "Adding Foreman repositories."

        - name: Ensure python-apt is installed
          command: >
            apt-get install python-apt -y -q
            creates=/usr/share/doc/python-apt


        -   apt_key: url=https://deb.theforeman.org/pubkey.gpg state=present

        -   apt_repository: repo='deb http://deb.theforeman.org/ jessie 1.14' state=present filename='foreman.list' update_cache='yes'
        -   apt_repository: repo='deb http://deb.theforeman.org/ plugins 1.14' state=present filename='foreman.list' update_cache='yes'


        -   debug:
                msg: "Will install needed packages."

        -   apt:
                package: "{{item}}"
                state: latest
                update_cache: yes
            with_items:
                - apache2
                - isc-dhcp-server
                - xinetd
                - tftpd
                - tftp
                - foreman-proxy

        -   debug:
                msg: "Configure networking."

        -   name: Enable IPv4 traffic forwarding (etc/sysctl.conf)
            lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.ip_forward" line="net.ipv4.ip_forward=1"

        -   name: Enable IPv4 traffic forwarding (/proc/sys/net/ipv4/ip_forward)
            command: echo 1 > /proc/sys/net/ipv4/ip_forward

        -   name: enable_masquarade
            shell: 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE'

# rest of iptables not in this playbook

        -   debug:
                msg: "Configure DHCP."

        -   file: path=/etc/dhcp/dhcpd.hosts state=touch

        -   copy: src=files/proxy-server/dhcp/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
            notify:
                - restart_DHCP

        - replace:
             path: /etc/dhcp/dhcpd.conf
             regexp: 'FIXME-SUBNET-PART'
             replace: "{{ ansible_eth1.ipv4.address.rpartition('.')[0]  }}"
             backup: yes
        #
        - replace:
             path: /etc/dhcp/dhcpd.conf
             regexp: 'FIXME-IP'
             replace: "{{ ansible_eth1.ipv4.address }}"
             backup: yes


# FIXME-SUBNET -> subnet IP  ip in tftp.yml KK?
# FIXME-IP -> server ip in tftp.yml KK?

        -   debug:
                msg: "Configure TFTP."

        -   copy: src=files/proxy-server/tftp dest=/etc/xinetd.d/tftp
            notify:
                - restart_TFTP

# FIXME-IP -> server ip in tftp.yml

        -   name: Create TFTP directory
            file: path=/srv/tftp/ state=directory owner=foreman-proxy group=foreman-proxy mode=0775 recurse=yes


        - name: Make sure the tftp directories exist
          file: path="/srv/tftp/{{item}}" state=directory owner=foreman-proxy group=foreman-proxy mode=0775 recurse=yes
          with_items:
                - boot
                - poap.cfg
                - ztp.cfg
                - pxelinux.cfg

        -   name: Download and unpack Foreman Discovery Image
            unarchive:
                src: "http://downloads.theforeman.org/discovery/releases/3.2/fdi-image-latest.tar"
                dest: "/srv/tftp/boot"
                copy: no
                creates: /srv/tftp/boot/fdi-image/initrd0.img

        -   name: Download and unpack Syslinux archive
            unarchive:
                src: "https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-5.10.tar.gz"
                dest: "/tmp"
                copy: no
                creates: /srv/tftp/menu.c32

        -    name: Copy syslinux files
             shell: creates=/srv/tftp/menu.c32 cp {{ item.src }} {{ item.dest }}
             with_items:
               - { src: '/tmp/syslinux-5.10/com32/chain/chain.c32', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/lib/libcom32.c32', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/elflink/ldlinux/ldlinux.c32', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/libutil/libutil.c32', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/mboot/mboot.c32', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/memdisk/memdisk', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/core/pxelinux.0', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/mboot/mboot.c32 ', dest: '/srv/tftp' }
               - { src: '/tmp/syslinux-5.10/com32/menu/menu.c32', dest: '/srv/tftp' }


        -   debug:
                msg: "Configure Foreman Proxy."

        -   name: Create /etc/foreman-proxy/ssl/private_keys
            file: path=/etc/foreman-proxy/ssl/private_keys state=directory owner=root group=root mode=0775 recurse=yes

        -   name: Create /etc/foreman-proxy/ssl/certs
            file: path=/etc/foreman-proxy/ssl/certs state=directory owner=root group=root mode=0775

        -   name: Create /etc/foreman-proxy/settings.d
            file: path=/etc/foreman-proxy/ssl/certs state=directory owner=foreman-proxy group=foreman-proxy mode=0775


        -   name: Copy conf files
            copy: src=files/proxy-server/foreman-proxy/{{item}} dest=/etc/foreman-proxy/{{item}}
            with_items:
                - settings.yml
                - settings.d/bmc.yml
                - settings.d/dhcp.yml
                - settings.d/dhcp_isc.yml
                - settings.d/dhcp_isc.yml
                - settings.d/dns.yml
                - settings.d/dns_nsupdate.yml
                - settings.d/tftp.yml

        - replace:
             path: /etc/foreman-proxy/settings.yml
             regexp: 'FIXME-MASTERHOST'
             replace: "{{ foreman_master_hostname  }}"
             backup: yes
        #
        - replace:
             path: /etc/foreman-proxy/settings.yml
             regexp: 'FIXME-PROXYHOST'
             replace: "{{ ansible_fqdn  }}"
             backup: yes
        #
        - replace:
             path: /etc/foreman-proxy/settings.d/tftp.yml
             regexp: 'FIXME-IP'
             replace: "{{ ansible_eth1.ipv4.address  }}"
             backup: yes

        -   debug:
                msg:
                  - "Instalation from now on is manual. "
                  - "Please:"
                  - "generate certificates on Foreman master and copy them here. (script foreman-create-proxy-certificate.sh at {{ foreman_master_hostname  }}:~)"
                  - "add new foreman proxy in https://{{ foreman_master_hostname  }}/"
                  - "   - import IPv4 internal subnet"
                  - "   - regenerate PXE Default in Hosts > Provisioning Templates > Build PXE Default"
                  - "Afterwards start proxy using /etc/init.d/foreman-proxy restart"


# send generated keys from master to proxies

# sooo -> fetch from remote (i.e. master)
# after that copy key securely https://blog.confirm.ch/deploying-ssl-private-keys-with-ansible/

    handlers:
         -   name: restart_TFTP
             service: name=xinetd state=restarted

         -   name: restart_DHCP
             service: name=isc-dhcp-server state=restarted
